# Generated by Django 4.0.8 on 2023-02-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='slug',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
