# Generated by Django 4.0.8 on 2023-01-27 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cookie_name',
            new_name='cookie_value',
        ),
    ]
