# Generated by Django 4.0.8 on 2023-01-23 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100, 'Discount value must be lower than or equal to 100')]),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100, 'Discount value must be lower than or equal to 100')]),
        ),
        migrations.AlterField(
            model_name='productpoint',
            name='point',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5, 'Discount value must be lower than or equal to 100')]),
        ),
    ]
