# Generated by Django 4.0.8 on 2023-01-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_comment_date_verified_productmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hex_code',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
